[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "1.1.2"
authors = [
        "Kubewarden Developers <kubewarden@suse.de>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.2", features = [ "cargo", "env" ] }
clap_complete = "3.2"
directories = "4.0.1"
itertools = "0.10.3"
k8s-openapi = { version = "0.15.0", default-features = false, features = ["v1_24"] }
lazy_static = "1.4.0"
mdcat = "0.28"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.4.7" }
pretty-bytes = "0.2.2"
prettytable-rs = "^0.8"
pulldown-cmark = { version = "0.9.2", default-features = false }
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.4"
syntect = "5.0"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
url = "2.2.2"
walrus = "0.19.0"
wasmparser = "0.88"

[dev-dependencies]
tempfile = "3.3.0"
rstest = "0.15.0"
