[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "1.10.1"
authors = ["Kubewarden Developers <kubewarden@suse.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap_complete = "4.4"
clap = { version = "4.4", features = ["cargo", "env"] }
directories = "5.0.1"
flate2 = "1.0.28"
humansize = "2.1"
itertools = "0.12.1"
k8s-openapi = { version = "0.21.0", default-features = false, features = [
  "v1_29",
] }
lazy_static = "1.4.0"
pulldown-cmark-mdcat = { version = "2.1.1", default-features = false, features = [
  "regex-fancy",
] }
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.15.0" }
prettytable-rs = "^0.10"
pulldown-cmark = { version = "0.9.3", default-features = false }
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.31"
syntect = { version = "5.1", default-features = false, features = [
  "default-syntaxes",
  "parsing",
] }
tar = "0.4.40"
tiny-bench = "0.3"
tokio = { version = "^1.35.1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
url = "2.5.0"
walrus = "0.20.3"
wasmparser = "0.121"
time = "0.3.34"
semver = { version = "1.0.21", features = ["serde"] }

# This is required to have reqwest built using the `rustls-tls-native-roots`
# feature across all the transitive dependencies of kwctl
# This is required to have kwctl use the system certificates instead of the
# ones bundled inside of rustls
reqwest = { version = "0", default-features = false, features = [
  "rustls-tls-native-roots",
] }

[dev-dependencies]
rstest = "0.18.2"
tempfile = "3.10.0"
assert_cmd = "2.0.13"
predicates = "3.1.0"
testcontainers = "0.15"
