[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "1.4.2"
authors = [
        "Kubewarden Developers <kubewarden@suse.de>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap_complete = "4.0"
clap = { version = "4.0", features = [ "cargo", "env" ] }
directories = "4.0.1"
flate2 = "1.0.25"
itertools = "0.10.5"
k8s-openapi = { version = "0.17.0", default-features = false, features = ["v1_25"] }
lazy_static = "1.4.0"
# It's necessary to set the "static" feature in mdcat to avoid the usage of 
# native-ssl. Using the rustls instead. Otherwise, the build will fail due the 
# missing OpenSSL lib.
mdcat = { version = "1.0", default-features = false, features = ["static"] }
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.6.0" }
pretty-bytes = "0.2.2"
prettytable-rs = "^0.10"
pulldown-cmark = { version = "0.9.2", default-features = false }
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.16"
syntect = { version = "5.0" , default-features = false, features = ["parsing"] }
tar = "0.4.38"
tiny-bench = "0.2"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
url = "2.3.1"
walrus = "0.19.0"
wasmparser = "0.97"

# This is required to have reqwest built using the `rustls-tls-native-roots`
# feature across all the transitive dependencies of kwctl
# This is required to have kwctl use the system certificates instead of the
# ones bundled inside of rustls
reqwest = { version = "0", default-features = false, features = ["rustls-tls-native-roots"] }

[dev-dependencies]
rstest = "0.16.0"
tempfile = "3.3.0"
