[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "0.1.7"
authors = [
        "Flavio Castelli <fcastelli@suse.com>",
        "Rafael Fernández López <rfernandezlopez@suse.com>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.33.3"
directories = "3.0.2"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
kubewarden-policy-sdk = "0.2.3"
mdcat = "0.22"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.1.16" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.1.10" }
pretty-bytes = "0.2.2"
prettytable-rs = "^0.8"
pulldown-cmark = { version = "0.8", default-features = false }
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
sha2 = "0.9.5"
syntect = "4.5.0"
tokio-compat-02 = "0.2.0"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version= "0.2", features = ["fmt"] }
url = "2.2.0"
validator = { version = "0.13", features = ["derive"] }
walrus = "0.19.0"

[dev-dependencies]
tempfile = "3.2.0"

[patch."https://github.com/kubewarden/policy-fetcher"]
policy-fetcher = { path = "../policy-fetcher" }

[patch."https://github.com/kubewarden/policy-evaluator"]
policy-evaluator = { path = "../policy-evaluator" }