[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "1.7.0-rc2"
authors = ["Kubewarden Developers <kubewarden@suse.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap_complete = "4.1"
clap = { version = "4.0", features = ["cargo", "env"] }
directories = "5.0.1"
flate2 = "1.0.27"
humansize = "2.1"
itertools = "0.11.0"
k8s-openapi = { version = "0.19.0", default-features = false, features = [
        "v1_27",
] }
lazy_static = "1.4.0"
pulldown-cmark-mdcat = { version = "2.0.3", default-features = false, features = [
        "regex-fancy",
] }
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.11.3" }
prettytable-rs = "^0.10"
pulldown-cmark = { version = "0.9.3", default-features = false }
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.25"
syntect = { version = "5.0", default-features = false, features = [
        "default-syntaxes",
        "parsing",
] }
tar = "0.4.40"
tiny-bench = "0.3"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
url = "2.4.0"
walrus = "0.20.1"
wasmparser = "0.110"
time = "0.3.25"
semver = { version = "1.0.18", features = ["serde"] }

# This is required to have reqwest built using the `rustls-tls-native-roots`
# feature across all the transitive dependencies of kwctl
# This is required to have kwctl use the system certificates instead of the
# ones bundled inside of rustls
reqwest = { version = "0", default-features = false, features = [
        "rustls-tls-native-roots",
] }

[dev-dependencies]
rstest = "0.18.2"
tempfile = "3.8.0"
