[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "1.13.0-rc2"
authors = ["Kubewarden Developers <kubewarden@suse.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap_complete = "4.5"
clap = { version = "4.5", features = ["cargo", "env"] }
directories = "5.0.1"
flate2 = "1.0.29"
humansize = "2.1"
itertools = "0.13.0"
k8s-openapi = { version = "0.22.0", default-features = false, features = [
  "v1_30",
] }
lazy_static = "1.4.0"
pem = "3"
pulldown-cmark-mdcat = { version = "2.1.2", default-features = false, features = [
  "regex-fancy",
] }
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.17.6" }
rustls-pki-types = { version = "1", features = ["alloc"] }
prettytable-rs = "^0.10"
pulldown-cmark = { version = "0.9.3", default-features = false }
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
syntect = { version = "5.2", default-features = false, features = [
  "default-syntaxes",
  "parsing",
] }
tar = "0.4.40"
tiny-bench = "0.3"
tokio = { version = "^1.37.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
url = "2.5.0"
walrus = "0.20.3"
wasmparser = "0.209"
time = "0.3.36"
semver = { version = "1.0.22", features = ["serde"] }

# This is required to have reqwest built using the `rustls-tls-native-roots`
# feature across all the transitive dependencies of kwctl
# This is required to have kwctl use the system certificates instead of the
# ones bundled inside of rustls
reqwest = { version = "0", default-features = false, features = [
  "rustls-tls-native-roots",
] }

[dev-dependencies]
rstest = "0.20.0"
tempfile = "3.10.1"
assert_cmd = "2.0.14"
predicates = "3.1.0"
testcontainers = { version = "0.17", features = ["blocking"] }
