[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "0.2.5"
authors = [
        "Flavio Castelli <fcastelli@suse.com>",
        "Rafael Fernández López <rfernandezlopez@suse.com>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.14", features = [ "cargo", "env" ] }
clap_complete = "3.0.6"
directories = "4.0.1"
itertools = "0.10.1"
k8s-openapi = { version = "0.14.0", default-features = false, features = ["v1_22"] }
kube = { version = "0.68.0", default-features = false, features = ["client", "rustls-tls"] }
lazy_static = "1.4.0"
mdcat = "0.25.1"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.2.11" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.4.2" }
pretty-bytes = "0.2.2"
prettytable-rs = "^0.8"
pulldown-cmark = { version = "0.9.1", default-features = false }
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
syntect = "4.5.0"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version= "0.3", features = ["fmt"] }
url = "2.2.0"
validator = { version = "0.14", features = ["derive"] }
walrus = "0.19.0"
wasmparser = "0.82.0"

[dev-dependencies]
tempfile = "3.3.0"