name: fossa scanning
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'

# Declare default permissions as read only.
permissions: read-all

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{secrets.FOSSA_API_TOKEN}}
